### PR TITLE
[GH-22]:Added support for different sub types of slack messages.

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
Summary and Features Added:-

1. Added support for the following sub-type of slack messages:-
       i) BotMessage
       ii) JoinLeaveMessage
       iii) MeMessage
       
2. Fixed the bug when the user for a post is not found by creating a new intermediate user with the same userId.

3. Fixed the bug when the root post of a thread is deleted by creating a dummy post with the message "This message has been deleted".

### CODE REVIEW

**Comment by sadohert** [comment]
@nab-77 - Can you help us with a recommendation for reviewer on this change?

**Comment by nab-77** [comment]
@noxer can you please review. Thanks.

**Review by noxer — CHANGES_REQUESTED** [review]
Thank you very much. Looks good so far. One small request.

**Review by noxer — APPROVED** [review]
LGTM

**Pull request merged**
